GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO claude_ro;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO claude_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, UPDATE, DELETE ON TABLES TO claude_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO claude_ro;